package oop;

import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import oop.entities.DurableProductsInventory;
import oop.entities.PerishableProductsInventory;
import oop.events.ErrorEvent;
import oop.events.EventListener;
import oop.views.ProductTableModel;

/**
 *
 * @author Hemrik Balázs
 */
public class MainForm extends javax.swing.JFrame implements EventListener {
    
    AbstractTableModel tableModel;
    TableRowSorter<TableModel> sorter;
    
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        btDurableProducts.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlError = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProducts = new javax.swing.JTable();
        btPerishableProducts = new javax.swing.JButton();
        btDurableProducts = new javax.swing.JButton();
        lbTableName = new javax.swing.JLabel();
        btAddProduct = new javax.swing.JButton();

        dlError.setTitle("Error");

        javax.swing.GroupLayout dlErrorLayout = new javax.swing.GroupLayout(dlError.getContentPane());
        dlError.getContentPane().setLayout(dlErrorLayout);
        dlErrorLayout.setHorizontalGroup(
            dlErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dlErrorLayout.setVerticalGroup(
            dlErrorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbProducts);

        btPerishableProducts.setText("Perishable Products");
        btPerishableProducts.setFocusable(false);
        btPerishableProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPerishableProductsActionPerformed(evt);
            }
        });

        btDurableProducts.setText("Durable Products");
        btDurableProducts.setFocusable(false);
        btDurableProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDurableProductsActionPerformed(evt);
            }
        });

        lbTableName.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lbTableName.setFocusable(false);

        btAddProduct.setText("AddProduct");
        btAddProduct.setFocusable(false);
        btAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1264, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbTableName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btDurableProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btPerishableProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDurableProducts)
                    .addComponent(btPerishableProducts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTableName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAddProduct)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDurableProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDurableProductsActionPerformed
        DurableProductsInventory inventory = new DurableProductsInventory();
        //inventory.addListener(this); -- :(
        tableModel = new ProductTableModel(inventory.getProducts());
        sorter = new TableRowSorter<>(tableModel);
        tbProducts.setModel(tableModel);
        tbProducts.setRowSorter(sorter);
        sorter.toggleSortOrder(0);
        lbTableName.setText("Durable Products");
    }//GEN-LAST:event_btDurableProductsActionPerformed

    private void btPerishableProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPerishableProductsActionPerformed
        PerishableProductsInventory inventory = new PerishableProductsInventory();
        //inventory.addListener(this); -- mennyi időt öltem ebbe de nem jó sajnos
        tableModel = new ProductTableModel(inventory.getProducts());
        sorter = new TableRowSorter<>(tableModel);
        tbProducts.setModel(tableModel);
        tbProducts.setRowSorter(sorter);
        sorter.toggleSortOrder(0);
        lbTableName.setText("Perishable Products");
    }//GEN-LAST:event_btPerishableProductsActionPerformed

    private void btAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddProductActionPerformed
        /*
        sajnos kifutottam az időből de nyilván ide jött volna a kód ami egy
        új termék felvételét kezdeményezi, a háttérben a kód nagyrésze meg van
        írva. A persistence réteg és az entititások felkészültek erre a funkcióra
        sajnos a nem működő kivételkezeléssel elvesztegettem az időt.
        */
        
    }//GEN-LAST:event_btAddProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.
                    getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).
                    log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddProduct;
    private javax.swing.JButton btDurableProducts;
    private javax.swing.JButton btPerishableProducts;
    private javax.swing.JDialog dlError;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTableName;
    private javax.swing.JTable tbProducts;
    // End of variables declaration//GEN-END:variables

    @Override
    public void handleErrorEvent(ErrorEvent evt) {
        //dlError.setVisible(true); -- ez így nem jó
    }

}
